In [5]:
import numpy as np
matrix_A = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix_B = np.array([[1,2,3], [4,5,6], [7,8,9]])


In [6]:
matrix_C = np.zeros((3,3))
print(matrix_A)
print(matrix_B)
print(matrix_C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
for i in range(len(matrix_A)): # Loop over rows of matrix_A
    for j in range(len(matrix_B[0])): # Loop over columns of matrix_B
        for k in range(len(matrix_B)): # Loop over rows of matrix_B
            matrix_C[i][j] += matrix_A[i][k] * matrix_B[k][j]

print(matrix_C)

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [8]:
#Use two for loops and get matrix C as the product of Matrix A & B
#Multiply A & B and store it in C 
#Single Threading
#Tiling
import numpy as np

matrix_A = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix_B = np.array([[1,2,3], [4,5,6], [7,8,9]])

#The np.dot function calculates the dot product between the two matrices
matrix_C = np.dot(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("Matrix B:")
print(matrix_B)

print("Matrix C:")
print(matrix_C)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix C:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
#Make a python code that is Multi Threaded 
#One prints Hello
#One prints World